language: python
python:
  - "3.8"
# command to install dependencies
services:
  - mysql
  - docker
before_install:
  - git submodule sync
  - git submodule update --init --recursive --remote
  - docker build -t ols tests/ols-docker
  - docker run -d -p 127.0.0.1:8080:8080 -t ols
  - docker ps -a
install:
  - pip install .[cicd]
# command to run tests
script:
  - coverage run -m nose tests.test_basic --verbose --cover-package=bio.ensembl
#  - coverage run -m nose tests.test_remote --verbose --cover-package=bio.ensembl
before_script:
  - mysql -e 'CREATE DATABASE ols_test_ontology;' -u root
after_success:
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: BkrSPAkOM5aTOpeyO9vZnHdZ0LF1PLk0r2HtcXN2eTMyiHoGXkl6VUjdAL8EkzI4gunW2GProdSIjHpf60WdiEmKAulMdJRI+xyUbuxnY31mwiikS9HYwqmPBbMTf0Mh2pMBngZRFs+gaFZDUMTfLfp+8MQfU1R54yb6hPuVt5I=
